[package]
name = "oracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1.4"
bitvec = "0.15.1"
flate2 = "1.0.11"
itertools = "0.8"
fnv = "1.0.6"
rayon = "1.2.0"
serde = { version = "1.0.99", features = ["derive", "rc"] }
indicatif = "0.11.0"
seahash = "3.0.6"
twox-hash = "1.5.0"
threadpool = "1.7.1"
once_cell = "1.0.2"
nalgebra = "0.18.1"
thincollections = "0.5.3"
crossbeam = "0.7.2"
opinionated = { path = "../opinionated/opinionated/"}
num-traits = "0.2"
wyhash = "0.3.0"
dashmap = "1.0.4"
num_cpus = "1.10.1"
finalfrontier = "0.6.1"
finalfusion-utils = "0.7.0"
finalfusion = "0.7.0"
finalfrontier-utils = "0.6.1"
rand_xorshift = "0.2.0"
rand = "0.6"

[target.'cfg(unix)'.dependencies]
mimalloc = { version = "0.1.6", default-features = false }

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
debug = true # Eventually remove this.... but good to valgrind

[dependencies.clap]
version = "2.33"
features = [ "suggestions", "color", "yaml", "wrap_help"]