[package]
name = "liboracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.2"
thincollections = "0.5.3"
wyhash = "0.3.0"
once_cell = "1.2.0"
opinionated = { path = "../../opinionated/opinionated/opinionated/"}
bytecount = "0.6.0"
bitpacking = "0.8.1"
flate2 = "1.0.11"
indicatif = "0.12.0"
serde = { version = "1.0.101", features = ["derive", "rc"] }
bincode = "1.2.0"
twox-hash = "1.5.0"
fasthash = { path = "../../../software/rust-fasthash/fasthash/" }