[package]
name = "liboracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.2"
thincollections = "0.5.3"
wyhash = "0.3.0"
once_cell = "1.2.0"
opinionated = { path = "../../opinionated/opinionated/opinionated/"}
finalfrontier = { path = "../../finalfrontier/"}
finalfusion = { path = "../../finalfusion-rust/" }
bytecount = "0.6.0"
rand = "0.6"
rand_core = "0.4"
rand_xorshift = "0.1"
flate2 = { version = "1.0.12", features = ["zlib"] }
indicatif = "0.12.0"
serde = { version = "1.0.101", features = ["derive", "rc"] }
fnv = "1.0.6"
twox-hash = "1.5.0"
stdinout = "0.4"
static_assertions = "1.0.0"
t1ha = "0.1"
