extern crate crossbeam;
extern crate thincollections;
extern crate wyhash;
extern crate once_cell;
extern crate opinionated;
extern crate bytecount;
extern crate bitpacking;
extern crate flate2;
extern crate serde;
extern crate bincode;
extern crate twox_hash;
extern crate finalfrontier;
extern crate finalfusion;
extern crate rand;

mod utils;
pub mod kmer_counting;
mod threads;
pub mod vocab;
pub mod embeddings;
