[package]
name = "oracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
bitvec = "0.15.2"
flate2 = "1.0.11"
itertools = "0.8"
fnv = "1.0.6"
rayon = "1.2.0"
serde = { version = "1.0.101", features = ["derive", "rc"] }
indicatif = "0.12.0"
seahash = "3.0.6"
twox-hash = "1.5.0"
once_cell = "1.2.0"
nalgebra = "0.18.1"
thincollections = "0.5.3"
crossbeam = "0.7.2"
opinionated = { path = "../../opinionated/opinionated/opinionated/"}
num-traits = "0.2"
wyhash = "0.3.0"
dashmap = "1.0.4"
num_cpus = "1.10.1"
rand_xorshift = "0.2.0"
rand = "0.7.2"
bitpacking = "0.8.1"

[target.'cfg(unix)'.dependencies]
mimalloc = { version = "0.1.9", default-features = false }

[dependencies.clap]
version = "2.33"
features = [ "suggestions", "color", "yaml", "wrap_help"]
