[package]
name = "pyracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[lib]
name = "pyracular"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.3"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[dependencies]
bytecount = "0.6.1"
twox-hash = "1.5.0"
liboracular = { path = "../liboracular/" }
crossbeam = "0.8.0"
mimalloc = { version = "0.1.22", default-features = false }
rand = "0.7.3"
rand_xoshiro = "0.4.0"


