[package]
name = "pyracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[lib]
name = "string_sum"
crate-type = ["cdylib", "lib"]

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]

[dependencies]
twox-hash = "1.5.0"


