[package]
name = "pyracular"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

[lib]
name = "pyracular"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.1"
features = ["extension-module"]

[dependencies]
twox-hash = "1.5.0"
liboracular = { path = "../liboracular/" }
crossbeam = "0.7.3"
rayon = "1.3.0"


